tempo:
  namespace: tempo
  name: tempo

##############################################
# SUBCHART: helper-odf-bucket-secret
# Creates a Secret that Tempo requires
#
# A Kubernetes Job is created, that reads the
# data from the Secret and ConfigMap and
# creates a new secret for Tempo.
##############################################
helper-odf-bucket-secret:
  # -- Enable Job to create a Secret for TempoStack.
  # @default -- false
  enabled: true

  # -- Syncwave for Argo CD.
  # @default -- 3
  syncwave: 3

  # -- Namespace where TempoStack is deployed and where the Secret shall be created.
  namespace: tempo

  # -- Name of Secret that shall be created.
  secretname: tempo-bucket-secret

  # Bucket Configuration
  bucket:
    # -- Name of the Bucket shall has been created.
    name: *bucketname

  # -- Keys that shall be used to create the Secret.
  keys:
    # -- Overwrite access_key_id key.
    # @default -- access_key_id
    access_key_id: access_key_id
    # -- Overwrite access_key_secret key.
    # @default -- access_key_secret
    access_key_secret: access_key_secret
    # -- Overwrite bucket key.
    # @default -- bucket
    bucket: bucket
    # -- Overwrite endpoint key.
    # @default -- endpoint
    endpoint: endpoint