---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-rhdh
  namespace: rhdh
data:
  app-config.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: https://rhdh.{{ .Values.clusterDomain }}