---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-rhdh
  namespace: {{ .Values.rhdh.namespace }}
data:
  app-config.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: https://rhdh.{{ .Values.clusterDomain }}