---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-rhdh
  namespace: {{ .Values.rhdh.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  app-config.yaml: |
    permission:
      enabled: true
            
    app:
      title: Portal de Desarrolladores - RHCL Demo
      baseUrl: https://rhdh.{{ .Values.clusterDomain }}

    backend:
      baseUrl: https://rhdh.{{ .Values.clusterDomain }}
      cors:
        origin: https://rhdh.{{ .Values.clusterDomain }}

    signInPage: oidc
    auth:
      session:
        secret: ${BACKEND_SECRET}
      environment: production
      providers:
        oidc:
          production:
            prompt: login
            metadataUrl: https://sso.{{ .Values.clusterDomain }}/realms/{{ .Values.keycloak.realmName }}/.well-known/openid-configuration
            clientId: ${AUTHENTICATION_OIDC_CLIENT_ID}
            clientSecret: ${AUTHENTICATION_OIDC_CLIENT_SECRET}
            signIn:
              resolvers:
                - resolver: preferredUsernameMatchingUserEntityName
    
    catalog:
      rules:
        - allow: [Component, System, API, Resource, Location, Template, Domain, Group, User]
      providers:
        keycloakOrg:
          default:
            baseUrl: https://sso.{{ .Values.clusterDomain }}/
            realm: {{ .Values.keycloak.realmName }}
            loginRealm: {{ .Values.keycloak.realmName }}
            clientId: ${AUTHENTICATION_OIDC_CLIENT_ID}
            clientSecret: ${AUTHENTICATION_OIDC_CLIENT_SECRET}
            schedule:
              frequency: { minutes: 2}
              timeout: { minutes: 1}
              initialDelay: { seconds: 15 }
            signIn:
              resolvers:
                - resolver: emailMatchingUserEntityProfileEmail

    kubernetes:
      serviceLocatorMethod:
        type: multiTenant
      clusterLocatorMethods:
        - clusters:
          - name: dev-cluster
            url: {{ .Values.kubernetes.apiUrl }}
            authProvider: serviceAccount
            skipTLSVerify: true
            serviceAccountToken: ${token}
          type: config
      customResources:
        - group: tekton.dev
          apiVersion: v1
          plural: pipelineruns
        - group: tekton.dev
          apiVersion: v1
          plural: taskruns
        - group: route.openshift.io
          apiVersion: v1
          plural: routes
        - group: sonataflow.org
          apiVersion: v1alpha08
          plural: sonataflows