---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
  namespace: rhdh
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  BACKEND_SECRET: N4KQcvTEIi6lAMGB5S0vHvBZdeAh789+J
  AUTHENTICATION_OIDC_CLIENT_ID: backstage
  AUTHENTICATION_REALM: backstage
  AUTHENTICATION_OIDC_CLIENT_SECRET: hj6tBlXDh4jvSDIHEXmZFQpgJAW4dMZw
  AUTHENTICATION_OIDC_BASE_URL: https://sso.apps.cluster-xg5rr.dynamic2.redhatworkshops.io/
  AUTHENTICATION_OIDC_METADATA_URL: https://sso.apps.cluster-xg5rr.dynamic2.redhatworkshops.io//realms/backstage/.well-known/openid-configuration
  GITLAB_TOKEN: glpat-jelIFZsnkJSRs0VAFXqpDW86MQp1OjEH.01.0w1oeny5j
  SESSION_SECRET: superSecret