---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
  namespace: rhdh
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  BACKEND_SECRET: N4KQcvTEIi6lAMGB5S0vHvBZdeAh789+J
  AUTHENTICATION_OIDC_CLIENT_ID: {{ .Values.keycloak.clientId }}
  AUTHENTICATION_REALM: {{ .Values.keycloak.realmName }}
  AUTHENTICATION_OIDC_CLIENT_SECRET: {{ .Values.keycloak.secret }}
  AUTHENTICATION_OIDC_BASE_URL: https://sso.{{ .Values.clusterDomain }}/
  AUTHENTICATION_OIDC_METADATA_URL: https://sso.{{ .Values.clusterDomain }}/realms/{{ .Values.keycloak.realmName }}/.well-known/openid-configuration
  GITLAB_TOKEN: glpat-jelIFZsnkJSRs0VAFXqpDW86MQp1OjEH.01.0w1oeny5j
  SESSION_SECRET: superSecret