---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-plugins-rhdh
  namespace: {{ .Values.rhdh.namespace }}
  labels:
    rhdh.redhat.com/ext-config-sync: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  dynamic-plugins.yaml: |
    includes:
    - dynamic-plugins.default.yaml
    plugins:
    - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github
      disabled: false
    - package: ./dynamic-plugins/dist/backstage-community-plugin-rbac
      disabled: false
...