---
apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  name: {{ .Values.rhdh.name }}
  namespace: {{ .Values.rhdh.namespace }}
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  database:
    enableLocalDb: true
  application:
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    appConfig:
      configMaps:
        - name: app-config-rhdh
      mountPath: /opt/app-root/src
    extraFiles:
      mountPath: /opt/app-root/etc
      configMaps:
        - name: rbac-policies
    extraEnvs:
      envs:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
      secrets:
        - name: rhdh-secrets
        - name: kubernetes-sa-token
    replicas: 1
    route:
      enabled: true
      host: rhdh.{{ .Values.clusterDomain }}
      subdomain: {{ .Values.clusterDomain }}
  deployment:
    patch:
      spec:
        template:
          spec:
            automountServiceAccountToken: true