apiVersion: extensions.kuadrant.io/v1alpha1
kind: PlanPolicy
metadata:
  name: {{ .Values.apiSample.name }}-plan
  namespace: {{ .Values.apiSample.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ .Values.apiSample.name }}-route
  plans:
    - tier: gold
      predicate: |
        has(auth.identity) && auth.identity.metadata.annotations["secret.kuadrant.io/plan-id"] == "gold"
      limits:
        daily: 100
    - tier: silver
      predicate: |
        has(auth.identity) && auth.identity.metadata.annotations["secret.kuadrant.io/plan-id"] == "silver"
      limits:
        daily: 50
    - tier: bronze
      predicate: |
        has(auth.identity) && auth.identity.metadata.annotations["secret.kuadrant.io/plan-id"] == "bronze"
      limits:
        daily: 10