repoURL: 'https://github.com/mikeintoch/mi-repo-demos.git'
targetRevision: HEAD

gitlab:
  namespace: gitlab-system

gitops:
  namespace: other-gitops

global:
  clusterDomain: apps.cluster-b764h.dyn.redhatworkshops.io