apiVersion: v2
name: rhcl-demo
description: Helm Chart para automatizar la demo completa de Red Hat Connectivity Link (Service Mesh 3.x + Kuadrant)
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - connectivity-link
  - service-mesh-v3
  - kuadrant
  - gateway-api
  - gitops
  - openshift