apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: developer-hub
  namespace: {{ .Values.gitops.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: apps/charts/rhdh
    helm:
      parameters:
        - name: "clusterDomain"
          value: "{{ .Values.global.clusterDomain }}"
        - name: "kubernetes.apiUrl"
          value: "{{ .Values.global.apiUrl }}"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.rhdh.namespace }}
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
  ignoreDifferences:
    - group: rhdh.redhat.com
      kind: Backstage
      jsonPointers:
        - /metadata/finalizers
        - /status