repoURL: 'https://github.com/mikeintoch/mi-repo-demos.git'
targetRevision: HEAD

gitops:
  namespace: other-gitops

servicemesh:
  namespace: istio-system

kuadrant:
  namespace: kuadrant-system

apiSample:
  namespace: api-sample

gateway:
  namespace: api-gateway

rhdh:
  namespace: rhdh