apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh
  namespace: {{ .Values.gitops.namespace }}
spec:
  project: default
ignoreDifferences:
    - group: sailoperator.io
      kind: Istio
      jsonPointers:
        - /metadata/labels
        - /metadata/finalizers
    - group: operators.coreos.com
      kind: Subscription
      jsonPointers:
        - /spec/startingCSV
    - group: sailoperator.io
      kind: Ztunnel
      jsonPointers:
        - /metadata/finalizers
        - /metadata/labels
        # El operador muta las imágenes dinámicamente según la arquitectura del nodo (x86, ARM, etc.)
        - /spec/image 
        # Ignora el estatus de salud del DaemonSet que cambia con los reinicios de nodos
        - /status
    - group: sailoperator.io
      kind: IstioCNI
      jsonPointers:
        - /metadata/finalizers
        - /metadata/labels
        # Parches de seguridad de red específicos que OpenShift inyecta en vivo
        - /spec/cni 
        - /status
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: apps/charts/service-mesh
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.servicemesh.namespace }}
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true