apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: developer-hub
  namespace: {{ .Values.gitops.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: apps/charts/tempostack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.tempo.namespace }}
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true