gateway:
  name: external
  className: istio
  namespace: api-gateway

apiSample:
  name: camel-service
  namespace: api-sample
  servicePort: 80 

clusterDomain: apps.cluster-jtj8w.dynamic2.redhatworkshops.io