gateway:
  name: external
  className: istio
  namespace: api-gateway

apiSample:
  name: camel-service
  namespace: api-sample
  servicePort: 80 

global:
  clusterDomain: app.<cluster-name>.<cluster-domain>