apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tempo-bucket-secret
  namespace: tempo
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: kubernetes-local # Un Store previamente configurado que apunta al mismo clúster
    kind: ClusterSecretStore
  target:
    name: tempo-bucket-secret # El secreto que se va a CREAR automáticamente
    template:
      engineVersion: v2
      data:
        # Aquí haces las concatenaciones de forma dinámica usando tags de tipo Jinja
        endpoint: "https://{{ .bucket_host }}:{{ .bucket_port }}"
        bucket: "{{ .bucket_name }}"
        access_key_id: "{{ .access_key_id }}"
        access_key_secret: "{{ .access_key_secret }}"
  data:
    # Aquí mapeas los orígenes dinámicos (ConfigMaps y Secrets)
    - secretKey: bucket_host
      remoteRef:
        key: tempo-bucket # Nombre del CM
        property: BUCKET_HOST
        kind: ConfigMap
    - secretKey: bucket_port
      remoteRef:
        key: tempo-bucket
        property: BUCKET_PORT
        kind: ConfigMap
    - secretKey: bucket_name
      remoteRef:
        key: tempo-bucket
        property: BUCKET_NAME
        kind: ConfigMap
    - secretKey: access_key_id
      remoteRef:
        key: tempo-bucket # Nombre del Secret original
        property: AWS_ACCESS_KEY_ID
    - secretKey: access_key_secret
      remoteRef:
        key: tempo-bucket
        property: AWS_SECRET_ACCESS_KEY