rhdh:
  namespace: rhdh
  name: rhdh

clusterDomain: apps.cluster-cwgqs.dynamic2.redhatworkshops.io
keycloak:
  name: keycloak
  namespace: keycloak
  realmName: backstage
  clientId: backstage
  secret: hj6tBlXDh4jvSDIHEXmZFQpgJAW4dMZw

kubernetes:
  apiUrl: https://api.cluster-cwgqs.dynamic2.redhatworkshops.io:6443

kuadrant:
  pluginVersion: v0.3.0