rhdh:
  namespace: rhdh
  name: rhdh

clusterDomain: apps.<cluster-domain>

keycloak:
  name: keycloak
  namespace: keycloak
  realmName: backstage
  clientId: backstage
  secret: hj6tBlXDh4jvSDIHEXmZFQpgJAW4dMZw

kubernetes:
  apiUrl: https://api.<cluster-domain>:6443

kuadrant:
  pluginVersion: v<version>
  backendCheckSum: <npmchecksum>
  frontendCheckSum: <npmchecksum>