apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiSample.name }}
  namespace: {{ .Values.apiSample.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
  - name: http
    port: {{ .Values.apiSample.servicePort }}      # Escucha en el 80
    targetPort: {{ .Values.apiSample.containerPort }} # Envía al 8080
  selector:
    app: {{ .Values.apiSample.name }}