repoURL: 'https://github.com/mikeintoch/mi-repo-demos.git'
targetRevision: HEAD

gitops:
  namespace: other-gitops

servicemesh:
  namespace: istio-system

kuadrant:
  namespace: kuadrant-system
  pluginVersion: v0.4.0
  backendCheckSum: sha512-OOkfAbnFxuOkBjvQMUqkd/TtP/yrXr15yQ/Xel880kdgZk39CPlQzVdOS3VXmcLa/Y9toI9nTbyCNqtXAD2C/g==
  frontendCheckSum: sha512-ewW/eOoHcK8MqmhyGzFQvnU8yQkvRpQxhb/GLZbAyWwWpmA/zju2qwFWXx49eBcy9RIlfO2rwS8sQC7do3dfGA==

apiSample:
  namespace: api-sample

gateway:
  namespace: api-gateway

rhdh:
  namespace: rhdh

tempo:
  namespace: tempo

global:
  clusterApi: https://api.cluster-hkvkn.dyn.redhatworkshops.io:6443
  clusterDomain: apps.cluster-hkvkn.dyn.redhatworkshops.io
