repoURL: 'https://github.com/mikeintoch/mi-repo-demos.git'
targetRevision: HEAD

gitops:
  namespace: other-gitops

servicemesh:
  namespace: istio-system

kuadrant:
  namespace: kuadrant-system
  pluginVersion: v0.3.0
  backendCheckSum: sha512-TWqq/0qW+ks3rNUSBF93/1Gw1ADu1MMVlQwl1xXbQpzPWyabZm/2F9MFsznl+3DQ16/w/9e7QPNS7DiTis2urw==
  frontendCheckSum: sha512-v1AgCXqouFlpINPWUnNDfuayO1krkRY5XJLPsne4mzBiKp5dDY993Zu+YdRVHsrrIbuNoRUcotWOZqjLwuLWuw==

apiSample:
  namespace: api-sample

gateway:
  namespace: api-gateway

rhdh:
  namespace: rhdh

tempo:
  namespace: tempo

global:
  clusterApi: https://api.cluster-s9tpc.dyn.redhatworkshops.io:6443
  clusterDomain: apps.cluster-s9tpc.dyn.redhatworkshops.io
