repoURL: 'https://github.com/mikeintoch/mi-repo-demos.git'
targetRevision: HEAD

gitops:
  namespace: other-gitops

servicemesh:
  namespace: istio-system

kuadrant:
  namespace: kuadrant-system

apiSample:
  namespace: api-sample

gateway:
  namespace: api-gateway

rhdh:
  namespace: rhdh

tempo:
  namespace: tempo

global:
  clusterApi: https://api.cluster-bgkrq.dynamic2.redhatworkshops.io:6443
  clusterDomain: apps.cluster-bgkrq.dynamic2.redhatworkshops.io