apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: {{ .Values.servicemesh.controlPlaneName }}
  annotations:
    # Wave 2: Argo CD esperará a que el operador (Wave 1) esté listo antes de aplicar esto
    argocd.argoproj.io/sync-wave: "1"
spec:
  namespace: {{ .Values.servicemesh.namespace }}
  profile: ambient
  global:
    platform: openshift
  pilot:
    trustedZtunnelNamespaces: {{ .Values.servicemesh.namespace }}
  meshConfig:
    discoverySelectors:
      - matchLabels:
          istio-discovery: enabled