---
apiVersion: v1
kind: Namespace
metadata:
  name: other-gitops
  labels:
    kubernetes.io/metadata.name: other-gitops
    istio-discovery: enabled
  annotations:
    openshift.io/display-name: API Gateway Namespace
    istio-discovery: enabled
    argocd.argoproj.io/managed-by: other-gitops
    # Wave 1: Le dice a Argo CD que ejecute esto antes de cualquier otra cosa
    argocd.argoproj.io/sync-wave: "0"
...
