---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-postgres
  namespace: {{ .Values.gitlab.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-postgres
  template:
    metadata:
      labels:
        app: gitlab-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_DB
              value: gitlab
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: gitlab-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitlab-db-secret
                  key: password
          volumeMounts:
            - name: postgres-storage
              mountPath: /data
              subPath: postgres-data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: gitlab-postgres-pvc
...
