---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-redis-secret
  namespace: {{ .Values.gitlab.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
data:
  password: YXZlcnlzZWN1cmVwYXNzd29yZA==
...