apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: gitlab-bucket
  namespace: {{ .Values.gitlab.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  generateBucketName: gitlab-bucket
  storageClassName: openshift-storage.noobaa.io