apiSample:
  name: camel-service
  namespace: api-sample
  image: quay.io/mdelgadi/camel-service
  replicas: 1
  # Añadimos los puertos aquí para que sea dinámico
  servicePort: 80     # El puerto que expone el Service hacia la malla
  containerPort: 8080 # El puerto real donde escucha tu aplicación/contenedor

clusterDomain: apps.cluster-pmbdz.dynamic2.redhatworkshops.io